### ISSUE TITLE
Games Not Ending

### ISSUE THREAD

**Issue by Scryrz** [LoyalFTW/CrossGambling#10]
Posting this here in addition to my Curseforge comment:

There's currently a non-reproducible issue occuring where on random games, even though everybody rolls, the addon will not complete the game and announce a winner and instead keep it active. The roll window shows everyone as having rolled but there's no annoucnement for winner. No LUA errors are being thrown and we haven't found a way to reliably reproduce this.

**Comment by LoyalFTW** [comment]
Hopefulyl fixed with the new additions
