### ISSUE TITLE
When 2 people tie, the round breaks

### ISSUE THREAD

**Issue by Gogo1951** [LoyalFTW/CrossGambling#11]
Doing some gambling between pulls...

 [R] [Gogopriest]: CrossGambling: A new game has been started! Type 1 to join! (-1 to withdraw) 
 [R] [Gogopriest]: Game Mode - Classic - Wager - 1,000g 
 [R] [Squirtie]: 1 
 [R] [Vladidaddy]: 1 
 [R] [Gogopriest]: 1 
 [R] [Stickypants]: 1 
 [R] [Umaddonriel]: 1 
 [R] [Zigosaurus]: 1 
 [R] [Brollun]: 1 
 [R] [Bàbayaga]: 1 
 [R] [Nikoleap]: 1 
 [R] [Gogopriest]: Last Call to Enter 
 [R] [Gogopriest]: Entries have closed. Roll now! 
 [R] [Gogopriest]: Type /roll 1000 
 [R] [Budh]: 1 
 Brollun rolls 750 (1-1000) 
 [R] [Budh]: fk 
 [R] [Budh]: lol 
 Umaddonriel rolls 703 (1-1000) 
 Stickypants rolls 792 (1-1000) 
 Squirtie rolls 576 (1-1000) 
 Bàbayaga rolls 136 (1-1000) 
 Nikoleap rolls 923 (1-1000) 
 Gogopriest rolls 418 (1-1000) 
 Zigosaurus rolls 923 (1-1000) 
 Vladidaddy rolls 71 (1-100) 
 [R] [Vladidaddy]: OOOF 
 Vladidaddy rolls 133 (1-1000) 
 [R] [Gogopriest]: High end tie breaker! Zigosaurus and Nikoleap /roll 1000 now! 
 Zigosaurus rolls 304 (1-1000) 
 Nikoleap rolls 987 (1-1000) 
 [R] [Gogopriest]: No winners this round!

**Comment by LoyalFTW** [comment]
I'm not sure why this broke the code looks correct and when I test it it seems to work if you can get me an error log if there was one that would be helpful.

**Comment by Gogo1951** [comment]
I don't raid much any more. Sorry mate. Had this issue 2-3 times when I was running GDKPs back in the day, once we got it we tried to reproduce it back then and were able to. But I don't have access to raid groups any more. Cheers!
