### ISSUE TITLE
Add "Branding" so users know what's coming from the add-on

### ISSUE THREAD

**Issue by Gogo1951** [LoyalFTW/CrossGambling#12]
Suggest adding the name of the logo before every message sent from the add-on. Something like "{rt2} CrossGalbming : " - that would add a coin and the name of the add-on.

I get most people can tell the difference, but you always get that one guy, "Why did you say that?" 

Plus, it's good branding to help promote the add-on.

 [R] [Gogopriest]: {rt2} CrossGalbming : Zigosaurus owes Bàbayaga 714 gold! 
 [R] [Gogopriest]: {rt2} CrossGalbming : A new game has been started! Type 1 to join! (-1 to withdraw) 
 [R] [Gogopriest]: {rt2} CrossGalbming : Game Mode - Classic - Wager - 1,000g 
 [R] [Squirtie]: 1 
 [R] [Vladidaddy]: 1 
 [R] [Gogopriest]: 1 
 [R] [Stickypants]: 1 
 [R] [Umaddonriel]: 1 
 [R] [Zigosaurus]: 1 
 [R] [Brollun]: 1 
 [R] [Bàbayaga]: 1 
 [R] [Nikoleap]: 1 
 [R] [Gogopriest]: {rt2} CrossGalbming : Last Call to Enter 
 [R] [Gogopriest]: {rt2} CrossGalbming : Entries have closed. Roll now! 
 [R] [Gogopriest]: {rt2} CrossGalbming : Type /roll 1000 
 Brollun rolls 750 (1-1000) 
 Umaddonriel rolls 703 (1-1000) 
 Stickypants rolls 792 (1-1000) 
 Squirtie rolls 576 (1-1000) 
 Bàbayaga rolls 136 (1-1000) 
 Nikoleap rolls 923 (1-1000) 
 Gogopriest rolls 418 (1-1000) 
 Zigosaurus rolls 923 (1-1000) 
 Vladidaddy rolls 71 (1-100) 
 [R] [Vladidaddy]: OOOF 
 Vladidaddy rolls 133 (1-1000) 
 [R] [Gogopriest]: {rt2} CrossGalbming : High end tie breaker! Zigosaurus and Nikoleap /roll 1000 now! 
 Zigosaurus rolls 304 (1-1000) 
 Nikoleap rolls 987 (1-1000) 
 [R] [Gogopriest]: {rt2} CrossGalbming : No winners this round!

**Comment by LoyalFTW** [comment]
I might add it not sure. Sometimes to much text is bothersome to people.
