### ISSUE TITLE
Add summary of how CrossGambling works

### ISSUE THREAD

**Issue by Gogo1951** [LoyalFTW/CrossGambling#13]
[R] [Gogopriest]: {rt2} CrossGalbming : A new game has been started! 
[R] [Gogopriest]: {rt2} CrossGalbming : Game Mode - Classic - Wager - 1,000g
[R] [Gogopriest]: {rt2} CrossGalbming : It's easy to play, and there's always a winner! Participants each roll the wager amount -- type "/roll 1000" when instructed -- and then the low roller pays the high roller the difference between their rolls. Are you feeling lucky?
[R] [Gogopriest]: {rt2} CrossGalbming : Type "1" to participate! (You can also type "-1" to withdraw.)

**Comment by LoyalFTW** [comment]
I'm going to be adding something like that in the future. But rather have it look a lot less cluttered
