### ISSUE TITLE
gamble session overall debt tracker

### ISSUE THREAD

**Issue by Hoellentier** [LoyalFTW/CrossGambling#14]
Would it be possible to add some sort of gamble sessions that keeps track of multiple gambles?

As an example we gambled while leveling in different areas but in a group. So we kept track of it in a spreadsheet and when finished calculated everything. It would be nice if it would be possible to start a gamble session and then when ending the session get some kind of output where it tells who owes who. Basically a more indepth stats tab since stats only shows overall winnings and losses but not to whom.

**Comment by LoyalFTW** [comment]
I have had that idea for a while back in the day but just never added it, I just now added it plus deathroll and sessions. Thank you.
