### ISSUE TITLE
Comma in Thousands

### ISSUE THREAD

**Issue by cartony** [LoyalFTW/CrossGambling#4]
Hey, is it possible to add a comma to indicate thousands? In my guild we frequently do rolls between 50k and 500k, and recently a few players have gotten burned by rolling for 500k when they thought it was 50k. 

With small text in WoW it is understandable how some people can glance and read 50000 as 500000, but if you added commas, or started displaying the amounts with k, it would be much less punishing for people. (It would not affect the "ease of rolling", as the addon could still command you to "/roll 500000" as is)

**Comment by LoyalFTW** [comment]
Fixed this.
